set(CTEST_PROJECT_NAME "Nanogear")
set(CTEST_NIGHTLY_START_TIME "23:00:00 GMT")
set(CTEST_DROP_METHOD http)
set(CTEST_DROP_SITE "dashboard.binaryhelix.net")
set(CTEST_DROP_LOCATION "/submit.php?project=Nanogear")
set(CTEST_DROP_SITE_CDASH TRUE)
