include(NanogearVersion)
set(CPACK_PACKAGE_NAME "Nanogear")
set(CPACK_PACKAGE_VENDOR "BinaryHelix")
set(CPACK_PACKAGE_VERSION_MAJOR ${NANOGEAR_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${NANOGEAR_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${NANOGEAR_PATCH})

set(CPACK_PACKAGE_FILE_NAME "nanogear-${NANOGEAR_MAJOR}.${NANOGEAR_MINOR}.${NANOGEAR_PATCH}")

set(CPACK_GENERATOR "TGZ")

set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES ".git")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "nanogear-src-${NANOGEAR_MAJOR}.${NANOGEAR_MINOR}.${NANOGEAR_PATCH}")

include(CPack)